import turtle

# def art():
#     window = turtle.Screen()
#     window.bgcolor('#e6ffcc')
#     hema  = turtle.Turtle()
#     hema.shape()
#     hema.speed(10)
#     hema.forward(100)
#     hema.backward(50)
#     hema.right(90)
#     hema.forward(100)
#     hema.right(90)
#     hema.forward(50)
#     hema.right(180)
#     hema.forward(100)
#     hema.penup()
#     hema.goto(150,-100)
#     hema.pendown()
#     hema.left(90)
#     hema.forward(100)
#     hema.right(135)
#     hema.forward(80)
#     hema.left(90)
#     hema.forward(80)
#     hema.right(135)
#     hema.forward(100)
#     hema.penup()
#     hema.goto(0,-110)
#     hema.pendown()
#     hema.left(90)
#     hema.forward(273)
#     hema.penup()
#     hema.goto(0,-120)
#     hema.pendown()
#     hema.forward(273)
#     window.exitonclick()

def art():
    window = turtle.Screen()
    window.bgcolor('yellow')
    basel = turtle.Turtle()
    basel.forward(100)
    basel.right(90)
    basel.forward(100)
    basel.right(90)
    basel.forward(100)
    basel.right(90)
    basel.forward(100)
    while True:
        basel.right(75)
        basel.forward(100)
        basel.right(90)
        basel.forward(100)
        basel.right(90)
        basel.forward(100)
        basel.right(90)
        basel.forward(100)

    window.exitonclick()


art()
